### ISSUE TITLE
Pogeo install error

### ISSUE THREAD

**Issue by NiliusJulius** [Noctem/Monocle#143]
I got everything working a few days ago, but today I tried to install everything on my raspberry pi, but when I'm running pip3 install -r requirements.txt, it errors out at the pogeo installation.

    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DS2_USE_EXACTFLOAT -DARCH_K8 -Igeometry -Igeometry/s2 -Igeometry/util/math -I/usr/local/include/python3.6m -c geometry/base/int128.cc -o build/temp.linux-armv7l-3.6/geometry/base/int128.o -Wno-ignore-qualifiers -fpermissive -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    geometry/base/int128.cc:11:25: fatal error: base/int128.h: No such file or directory
     #include "base/int128.h"
                             ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/local/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-q2dxvrq6/pogeo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8qa741i2-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-q2dxvrq6/pogeo/

So after I got this I tried it again on my windows machine and I got the same error.
Any ideas what might be causing this?

**Comment by xakiru** [comment]
It feels strange that's you've got the same issue on windows, I've just fresh installed Python/Git/Monocle yesterday, I have windows10 and it worked fine.
Make sure you've got the latest version of Python, Git and Monocle 
Run the installation from Git bash console

Otherwise check if you can install pogeo from : https://github.com/Noctem/pogeo

Hope this helps
Thanks,

**Comment by NiliusJulius** [comment]
I tried installing from github directly, same error. No idea what is causing it, because the file it says is missing is there.

**Comment by xakiru** [comment]
I noticed this in your error;
/tmp/pip-build-q2dxvrq6/pogeo/

I'm not sure about this but maybe you can try empty tmp/

Thanks,

**Comment by NiliusJulius** [comment]
Seems like that is just where it downloads or extracts it to or something, because those directories are empty/ do not exist

**Comment by xakiru** [comment]
How come your windows is showing paths like linux ? 
 /usr/local/bin/python3.6

**Comment by NiliusJulius** [comment]
The error is from the raspberry pi, so linux.
On windows it gives the same error (base/int128.h file not found).

**Comment by NiliusJulius** [comment]
I guess I found out what the problem is.
When I try to install pogeo on windows with python 2 it gives this error too. When I use python 3 it works flawlessly.
However I am using python 3 on linux, so why isn't it working there?

**Comment by xakiru** [comment]
Try to update to python3.6 or python3.5 atleast

**Comment by xakiru** [comment]
I've tried on my ubuntu server and I get the same issue, I'm not sure what causing this.

geometry/base/int128.cc:11:25: fatal error: base/int128.h: No such file or directory
 #include "base/int128.h"
                         ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1


I will let you know if i find how to fix this.
Thanks,

**Comment by xakiru** [comment]
Hi NiliusJulius,
I made a fork of https://github.com/Noctem/pogeo.git 
and changed the requirement.txt to fetch my pogeo fork instead of the main one the int128 was fixed.
But I got into another issue, maybe we should wait for main devs to look into this issue.


Here is a copy from pip log:

> ----------------------------------------
> Cleaning up...
>   Removing temporary dir /tmp/pip_build_root...
> Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-pzu97me1-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fprsi9dq-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-pzu97me1-build
> Exception information:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
>     requirement.install(install_options, global_options, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pip/req.py", line 707, in install
>     cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
>   File "/usr/lib/python3/dist-packages/pip/util.py", line 715, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> pip.exceptions.InstallationError: Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-pzu97me1-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fprsi9dq-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-pzu97me1-build




Thanks,

**Comment by NiliusJulius** [comment]
I have been trying to find a solution, but so far still don't have one.
Does anyone have an idea as to why it can't find base/int128.h?

**Comment by xakiru** [comment]
Tried everything, now I'm waiting for help .... because it's sounds like a problem in code ...

**Comment by Noctem** [comment]
So on the following platforms `pip install pogeo` should just install the binary wheel:

| OS | Architecture | Python |
| ------------- | ------------- | ------------- |
| Windows  | x64  | 3.5 |
| Windows  | x86 | 3.6 |
| Windows | x64 | 3.6 |
| Linux | x86 | 3.5 |
| Linux | x64  | 3.5 |
| Linux | x86 | 3.6 |
| Linux | x64 | 3.6 |
| macOS | x64 | 3.5 |
| macOS | x64 | 3.6 |

I may be able to cross-compile an ARM wheel soon. If you want to compile it yourself, gcc 6 or a recent version of clang are required.

**Comment by Noctem** [comment]
Closing this. Report any remaining issue [here](https://github.com/Noctem/pogeo/issues).

**Comment by NicoMatthaes** [comment]
Is there any way to get this problems solved on an ARM architecture ?
